from __future__ import annotations

from repave_engine.gate_registry import GateSpec, register_gate
from repave_engine.gate_runners import (
    run_amtool,
    run_ansible_lint,
    run_ansible_syntax_check,
    run_azure_policy,
    run_checkov,
    run_datadog_api_validate,
    run_datadog_dashboard,
    run_datadog_monitor,
    run_dockerfile_lint,
    run_docs_drift,
    run_go_lint,
    run_go_test,
    run_grafana_dashboard,
    run_helm_lint,
    run_helm_template,
    run_infracost,
    run_molecule,
    run_opa,
    run_promtool,
    run_provenance_drift,
    run_python_lint,
    run_python_test,
    run_secrets,
    run_terraform_fmt,
    run_terraform_test,
    run_terraform_validate,
    run_tflint,
    run_yamllint,
)

_TERRAFORM_ARTIFACT_TYPES = frozenset(
    {"terraform-module", "terraform-environment-stack", "observability"}
)
_ANSIBLE_ARTIFACT_TYPES = frozenset(
    {"ansible-role", "ansible-playbook-project", "ansible-collection"}
)
_OBSERVABILITY_ARTIFACT_TYPES = frozenset({"observability"})
_HELM_ARTIFACT_TYPES = frozenset({"helm-chart"})
_GITOPS_ARTIFACT_TYPES = frozenset({"gitops-deployment"})
_APP_SERVICE_ARTIFACT_TYPES = frozenset({"app-service"})
_SHARED_ARTIFACT_TYPES = frozenset(
    {
        "terraform-module",
        "terraform-environment-stack",
        "ansible-role",
        "ansible-playbook-project",
        "ansible-collection",
        "observability",
        "helm-chart",
        "gitops-deployment",
        "app-service",
        "opa-policy",
        "azure-policy",
        "checkov-policy",
    }
)
_OPA_GATE_ARTIFACT_TYPES = frozenset(
    {
        "terraform-module",
        "terraform-environment-stack",
        "opa-policy",
        "observability",
        "helm-chart",
        "gitops-deployment",
    }
)

register_gate(
    GateSpec(
        name="infracost",
        runner=run_infracost,
        artifact_types=_TERRAFORM_ARTIFACT_TYPES,
        artifact_paths=(".repave",),
    )
)
register_gate(
    GateSpec(
        name="terraform-fmt",
        runner=run_terraform_fmt,
        artifact_types=_TERRAFORM_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="terraform-validate",
        runner=run_terraform_validate,
        artifact_types=_TERRAFORM_ARTIFACT_TYPES,
        artifact_paths=(".terraform", ".terraform.lock.hcl"),
    )
)
register_gate(
    GateSpec(
        name="terraform-test",
        runner=run_terraform_test,
        artifact_types=_TERRAFORM_ARTIFACT_TYPES,
        artifact_paths=(".terraform", ".terraform.lock.hcl"),
    )
)
register_gate(
    GateSpec(
        name="tflint",
        runner=run_tflint,
        artifact_types=_TERRAFORM_ARTIFACT_TYPES,
        artifact_paths=(".tflint.d",),
    )
)
register_gate(
    GateSpec(
        name="checkov",
        runner=run_checkov,
        artifact_types=_TERRAFORM_ARTIFACT_TYPES | frozenset({"checkov-policy"}),
    )
)
register_gate(
    GateSpec(
        name="opa",
        runner=run_opa,
        artifact_types=_OPA_GATE_ARTIFACT_TYPES,
        artifact_paths=(".repave",),
    )
)
register_gate(
    GateSpec(
        name="azure-policy",
        runner=run_azure_policy,
        artifact_types=frozenset({"azure-policy"}),
    )
)
register_gate(
    GateSpec(
        name="secrets",
        runner=run_secrets,
        artifact_types=_SHARED_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="docs-drift",
        runner=run_docs_drift,
        artifact_types=_SHARED_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="provenance-drift",
        runner=run_provenance_drift,
        artifact_types=_SHARED_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="yamllint",
        runner=run_yamllint,
        artifact_types=_ANSIBLE_ARTIFACT_TYPES
        | _OBSERVABILITY_ARTIFACT_TYPES
        | _HELM_ARTIFACT_TYPES
        | _GITOPS_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="helm-lint",
        runner=run_helm_lint,
        artifact_types=_HELM_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="helm-template",
        runner=run_helm_template,
        artifact_types=_HELM_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="dockerfile-lint",
        runner=run_dockerfile_lint,
        artifact_types=_APP_SERVICE_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="python-lint",
        runner=run_python_lint,
        artifact_types=_APP_SERVICE_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="python-test",
        runner=run_python_test,
        artifact_types=_APP_SERVICE_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="go-lint",
        runner=run_go_lint,
        artifact_types=_APP_SERVICE_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="go-test",
        runner=run_go_test,
        artifact_types=_APP_SERVICE_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="promtool",
        runner=run_promtool,
        artifact_types=_OBSERVABILITY_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="amtool",
        runner=run_amtool,
        artifact_types=_OBSERVABILITY_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="grafana-dashboard",
        runner=run_grafana_dashboard,
        artifact_types=_OBSERVABILITY_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="datadog-dashboard",
        runner=run_datadog_dashboard,
        artifact_types=_OBSERVABILITY_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="datadog-monitor",
        runner=run_datadog_monitor,
        artifact_types=_OBSERVABILITY_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="datadog-api-validate",
        runner=run_datadog_api_validate,
        artifact_types=_OBSERVABILITY_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="ansible-lint",
        runner=run_ansible_lint,
        artifact_types=_ANSIBLE_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="ansible-syntax-check",
        runner=run_ansible_syntax_check,
        artifact_types=_ANSIBLE_ARTIFACT_TYPES,
    )
)
register_gate(
    GateSpec(
        name="molecule",
        runner=run_molecule,
        artifact_types=_ANSIBLE_ARTIFACT_TYPES,
        artifact_paths=(".molecule",),
    )
)
