from __future__ import annotations

import json
import subprocess
import urllib.error
import urllib.request
from typing import Any

from repave_engine.target_repo import ModuleRepository, _git_executable, _run_git


class GitHubError(RuntimeError):
    def __init__(self, status: int, message: str) -> None:
        super().__init__(message)
        self.status = status
        self.message = message


def ensure_github_repository(
    repository: ModuleRepository,
    token: str,
    *,
    description: str = "",
) -> str:
    if _repository_exists(repository, token):
        return "exists"

    try:
        _create_org_repository(repository, token, description=description)
        return "created"
    except GitHubError as exc:
        if exc.status == 404:
            _create_user_repository(repository, token, description=description)
            return "created"
        if exc.status == 422 and _name_already_exists(exc.message):
            return "exists"
        raise


def push_module_repository(
    repository: ModuleRepository,
    token: str,
    *,
    branch: str = "main",
) -> None:
    auth_url = f"https://x-access-token:{token}@github.com/{repository.owner}/{repository.name}.git"
    repo_dir = repository.local_path
    remotes = subprocess.run(
        [_git_executable(), "remote"],
        cwd=repo_dir,
        check=True,
        capture_output=True,
        text=True,
    )
    if "origin" in remotes.stdout.split():
        _run_git(["remote", "set-url", "origin", auth_url], cwd=repo_dir)
    else:
        _run_git(["remote", "add", "origin", auth_url], cwd=repo_dir)

    _run_git(["branch", "-M", branch], cwd=repo_dir)
    _run_git(["push", "-u", "origin", branch], cwd=repo_dir)


def _repository_exists(repository: ModuleRepository, token: str) -> bool:
    try:
        _github_request(
            "GET",
            f"/repos/{repository.owner}/{repository.name}",
            token,
        )
        return True
    except GitHubError as exc:
        if exc.status == 404:
            return False
        raise


def _create_org_repository(
    repository: ModuleRepository,
    token: str,
    *,
    description: str,
) -> None:
    _github_request(
        "POST",
        f"/orgs/{repository.owner}/repos",
        token,
        {
            "name": repository.name,
            "description": description
            or f"Terraform module generated by repave ({repository.name})",
            "private": False,
            "auto_init": False,
        },
    )


def _create_user_repository(
    repository: ModuleRepository,
    token: str,
    *,
    description: str,
) -> None:
    _github_request(
        "POST",
        "/user/repos",
        token,
        {
            "name": repository.name,
            "description": description
            or f"Terraform module generated by repave ({repository.name})",
            "private": False,
            "auto_init": False,
        },
    )


def _github_request(
    method: str,
    path: str,
    token: str,
    body: dict[str, Any] | None = None,
) -> dict[str, Any]:
    url = f"https://api.github.com{path}"
    payload = None if body is None else json.dumps(body).encode("utf-8")
    request = urllib.request.Request(  # nosec B310
        url,
        data=payload,
        method=method,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type": "application/json",
            "User-Agent": "repave-engine",
        },
    )

    try:
        with urllib.request.urlopen(request, timeout=30) as response:  # nosec B310
            raw = response.read().decode("utf-8")
            if not raw:
                return {}
            parsed = json.loads(raw)
            return parsed if isinstance(parsed, dict) else {}
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise GitHubError(exc.code, detail) from exc


def _name_already_exists(message: str) -> bool:
    lowered = message.lower()
    return "already exists" in lowered or "name already exists" in lowered
