from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from repave_engine.github import GitHubError, ensure_github_repository, push_module_repository
from repave_engine.target_repo import ModuleRepository


@dataclass(frozen=True)
class PullRequestPlan:
    title: str
    body: str
    branch: str
    files_root: Path
    repository: ModuleRepository


def plan_pull_request(
    *,
    module_name: str,
    blueprint_name: str,
    blueprint_version: str,
    standard_version: str,
    files_root: Path,
    repository: ModuleRepository,
    module_values: dict[str, Any] | None = None,
) -> PullRequestPlan:
    branch = "main"
    title = (
        f"Bootstrap Terraform module {repository.name} "
        f"(repave {blueprint_name}@{blueprint_version})"
    )

    summary_lines = [
        "## Summary",
        f"Generated by repave blueprint `{blueprint_name}` v{blueprint_version}.",
        "",
    ]
    values = module_values or {}
    if values.get("description"):
        summary_lines.append(f"- Description: {values['description']}")
    if values.get("cloud_provider"):
        summary_lines.append(f"- Cloud provider: `{values['cloud_provider']}`")
    if values.get("provider_services"):
        summary_lines.append(f"- Services in scope: `{values['provider_services']}`")
    summary_lines.extend(
        [
            f"- Module name: `{module_name}`",
            f"- Standard version: `{standard_version}`",
            f"- Target repository: `{repository.web_url}`",
            "- Output type: governed module repository",
            "- Gates: enforced before publish",
            "",
            "## Rollback",
            "Do not merge or delete the repository if this scaffold should be discarded.",
        ]
    )
    body = "\n".join(summary_lines) + "\n"
    return PullRequestPlan(
        title=title,
        body=body,
        branch=branch,
        files_root=files_root,
        repository=repository,
    )


def create_pull_request(plan: PullRequestPlan, *, github_token: str | None) -> str:
    if not github_token:
        return (
            "Dry-run: remote GitHub repository not created. Provide GITHUB_TOKEN to enable "
            "remote publish.\n"
            f"Target repository: {plan.repository.web_url}\n"
            f"Local repository: {plan.repository.local_path}\n"
            f"Planned branch: {plan.branch}\n"
            f"Planned title: {plan.title}"
        )

    try:
        action = ensure_github_repository(
            plan.repository,
            github_token,
            description=plan.title,
        )
        push_module_repository(plan.repository, github_token, branch=plan.branch)
    except GitHubError as exc:
        return (
            "GitHub publish failed.\n"
            f"Target repository: {plan.repository.web_url}\n"
            f"Local repository: {plan.repository.local_path}\n"
            f"Error ({exc.status}): {exc.message}"
        )
    except RuntimeError as exc:
        return (
            "GitHub publish failed while pushing the local repository.\n"
            f"Target repository: {plan.repository.web_url}\n"
            f"Local repository: {plan.repository.local_path}\n"
            f"Error: {exc}"
        )

    if action == "created":
        remote_action = "Created GitHub repository and pushed initial commit"
    else:
        remote_action = "Pushed initial commit to existing GitHub repository"

    return (
        f"{remote_action}.\n"
        f"Repository: {plan.repository.web_url}\n"
        f"Branch: {plan.branch}\n"
        f"Local repository: {plan.repository.local_path}"
    )
