from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from repave_engine.gate_registry import GateResult
from repave_engine.github import (
    GitHubError,
    ensure_github_repository,
    push_module_repository,
)
from repave_engine.github_repo_provision import (
    GitHubRepoProvisionSpec,
    format_provision_message,
    plan_provision,
    provision_github_repository,
)
from repave_engine.output_template import format_output_template
from repave_engine.pr_conventions import (
    PullRequestConventions,
    append_evidence_section,
    branch_name,
    load_pull_request_conventions,
)
from repave_engine.target_repo import ModuleRepository


@dataclass(frozen=True)
class PullRequestPlan:
    title: str
    body: str
    branch: str
    files_root: Path
    repository: ModuleRepository
    provision: GitHubRepoProvisionSpec | None = None


def plan_pull_request(
    *,
    blueprint_name: str,
    blueprint_version: str,
    standard_version: str,
    title_template: str,
    input_fields: tuple[str, ...],
    files_root: Path,
    repository: ModuleRepository,
    module_values: dict[str, Any],
    repo_root: Path | None = None,
    gate_results: tuple[GateResult, ...] = (),
    provision: GitHubRepoProvisionSpec | None = None,
) -> PullRequestPlan:
    conventions = (
        load_pull_request_conventions(repo_root)
        if repo_root is not None
        else PullRequestConventions()
    )
    name_hint = str(
        module_values.get("repo_name") or module_values.get("module_name") or blueprint_name
    )
    branch = branch_name(
        conventions.branch_prefix_generate,
        name_hint,
        blueprint_version,
    )
    title = format_output_template(title_template, module_values)

    summary_lines = [
        "## Summary",
        f"Generated by repave blueprint `{blueprint_name}` v{blueprint_version}.",
        "",
        "### Inputs",
    ]
    for field_name in input_fields:
        if field_name in module_values:
            summary_lines.append(f"- {field_name}: `{module_values[field_name]}`")
    output_label = (
        "governed GitHub repository provision"
        if provision is not None
        else "governed module repository"
    )
    summary_lines.extend(
        [
            "",
            f"- Standard version: `{standard_version}`",
            f"- Target repository: `{repository.web_url}`",
            f"- Output type: {output_label}",
            "- Gates: enforced before publish",
            "",
            "## Rollback",
            "Do not merge or delete the repository if this scaffold should be discarded.",
        ]
    )
    body = append_evidence_section(
        "\n".join(summary_lines) + "\n",
        gate_results,
        enabled=conventions.evidence_checklist,
    )
    return PullRequestPlan(
        title=title,
        body=body,
        branch=branch,
        files_root=files_root,
        repository=repository,
        provision=provision,
    )


def create_pull_request(plan: PullRequestPlan, *, github_token: str | None) -> str:
    if plan.provision is not None:
        return _create_provisioned_repository(plan, github_token=github_token)

    if not github_token:
        return (
            "Dry-run: remote GitHub repository not created. Provide GITHUB_TOKEN or GitHub App "
            "credentials to enable remote publish.\n"
            f"Repository name: {plan.repository.name}\n"
            f"Target repository: {plan.repository.web_url}\n"
            f"Local repository: {plan.repository.local_path}\n"
            f"Planned branch: {plan.branch}"
        )

    try:
        action = ensure_github_repository(
            plan.repository,
            github_token,
            description=plan.title,
        )
        push_module_repository(plan.repository, github_token, branch=plan.branch)
    except GitHubError as exc:
        return (
            "GitHub publish failed.\n"
            f"Target repository: {plan.repository.web_url}\n"
            f"Local repository: {plan.repository.local_path}\n"
            f"Error ({exc.status}): {exc.message}"
        )
    except RuntimeError as exc:
        return (
            "GitHub publish failed while pushing the local repository.\n"
            f"Target repository: {plan.repository.web_url}\n"
            f"Local repository: {plan.repository.local_path}\n"
            f"Error: {exc}"
        )

    if action == "created":
        remote_action = "Created GitHub repository and pushed initial commit"
    else:
        remote_action = "Pushed initial commit to existing GitHub repository"

    return (
        f"{remote_action}.\n"
        f"Repository: {plan.repository.web_url}\n"
        f"Branch: {plan.branch}\n"
        f"Local repository: {plan.repository.local_path}"
    )


def _create_provisioned_repository(
    plan: PullRequestPlan,
    *,
    github_token: str | None,
) -> str:
    if plan.provision is None:
        raise RuntimeError("provision plan missing for github-repo publish path")
    if not github_token:
        planned = plan_provision(plan.provision)
        return (
            "Dry-run: GitHub repository not provisioned. Provide GITHUB_TOKEN or GitHub App "
            "credentials to enable remote publish.\n"
            + format_provision_message(
                planned.create,
                planned.teams,
                overlay="planned",
                local_path=str(plan.repository.local_path),
                branch=plan.branch,
            )
        )

    try:
        created, grants = provision_github_repository(plan.provision, github_token)
        push_module_repository(plan.repository, github_token, branch=plan.branch)
    except GitHubError as exc:
        return (
            "GitHub repository provisioning failed.\n"
            f"Target repository: {plan.repository.web_url}\n"
            f"Local repository: {plan.repository.local_path}\n"
            f"Error ({exc.status}): {exc.message}"
        )
    except RuntimeError as exc:
        return (
            "GitHub repository provisioning failed while pushing the overlay commit.\n"
            f"Target repository: {plan.repository.web_url}\n"
            f"Local repository: {plan.repository.local_path}\n"
            f"Error: {exc}"
        )

    return format_provision_message(
        created,
        grants,
        overlay="pushed",
        local_path=str(plan.repository.local_path),
        branch=plan.branch,
    )
