apiVersion: repave.dev/v1beta1
kind: Blueprint
metadata:
  name: terraform-module-generic
  namespace: default
spec:
  version: "0.9.0"
  standard:
    source: standards/terraform-standards
    version: "1.1.0"
