apiVersion: repave.dev/v1alpha1
kind: Blueprint
metadata:
  name: terraform-module-generic
  namespace: default
spec:
  version: "0.1.0"
  standard:
    source: examples/standards
    version: "0.4.0"
