{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "repave-operator.fullname" . }}
  labels:
    {{- include "repave-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.githubToken }}
  github-token: {{ .Values.secrets.githubToken | quote }}
  {{- end }}
  {{- if .Values.secrets.githubAppId }}
  github-app-id: {{ .Values.secrets.githubAppId | quote }}
  {{- end }}
  {{- if .Values.secrets.githubAppInstallationId }}
  github-app-installation-id: {{ .Values.secrets.githubAppInstallationId | quote }}
  {{- end }}
  {{- if .Values.secrets.githubAppPrivateKey }}
  github-app-private-key: {{ .Values.secrets.githubAppPrivateKey | quote }}
  {{- end }}
{{- end }}
