apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.webhook.name }}
  labels:
    {{- include "repave-operator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "repave-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: {{ .Values.service.webhook.port }}
      targetPort: webhook-server
