{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "repave.fullname" . }}
  labels:
    {{- include "repave.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-token: {{ .Values.secrets.githubToken | quote }}
  session-secret: {{ .Values.secrets.sessionSecret | quote }}
  oidc-client-secret: {{ .Values.secrets.oidcClientSecret | quote }}
{{- end }}
