{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "repave.fullname" . }}
  labels:
    {{- include "repave.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-token: {{ .Values.secrets.githubToken | quote }}
  github-app-id: {{ .Values.secrets.githubAppId | quote }}
  github-app-installation-id: {{ .Values.secrets.githubAppInstallationId | quote }}
  github-app-private-key: {{ .Values.secrets.githubAppPrivateKey | quote }}
  session-secret: {{ .Values.secrets.sessionSecret | quote }}
  oidc-client-secret: {{ .Values.secrets.oidcClientSecret | quote }}
  api-token: {{ .Values.secrets.apiToken | quote }}
{{- end }}
